definitions:
  api.Choice:
    properties:
      choice:
        type: string
      description:
        type: string
      is_correct:
        type: boolean
    type: object
  api.ChoiceProblemRequest:
    properties:
      choices:
        items:
          $ref: '#/definitions/api.Choice'
        type: array
      description:
        type: string
    type: object
  api.ChoiceProblemResponse:
    properties:
      choices:
        items:
          $ref: '#/definitions/api.Choice'
        type: array
      description:
        type: string
      id:
        type: integer
    type: object
  api.LoginInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api.LoginResponse:
    properties:
      token:
        type: string
    type: object
  api.RegisterInfo:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  api.RegisterResponse:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  api.UserInfo:
    properties:
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  api.UserInfoResponse:
    properties:
      avatar_path:
        type: string
      create_at:
        type: string
      email:
        type: string
      phone:
        type: string
      user_id:
        type: integer
      user_name:
        type: string
    type: object
info:
  contact: {}
  title: Kayak Backend API
  version: 0.0.1
paths:
  /login:
    post:
      description: 用户登录
      parameters:
      - description: 用户登陆信息
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/api.LoginInfo'
      responses:
        "200":
          description: 用户登陆反馈
          schema:
            $ref: '#/definitions/api.LoginResponse'
        "400":
          description: 请求解析失败
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
  /logout:
    get:
      description: 用户退出
      responses:
        "200":
          description: 退出成功
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /ping:
    get:
      description: 测试服务器是否正常运行
      responses:
        "200":
          description: pong
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
  /problem/choice:
    get:
      description: 获取所有的选择题
      responses:
        "200":
          description: 选择题列表
          schema:
            items:
              $ref: '#/definitions/api.ChoiceProblemResponse'
            type: array
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /problem/choice/create:
    post:
      description: 创建选择题
      parameters:
      - description: 选择题信息
        in: body
        name: problem
        required: true
        schema:
          $ref: '#/definitions/api.ChoiceProblemRequest'
      - description: 是否公开
        in: query
        name: is_public
        type: boolean
      responses:
        "200":
          description: 创建成功
          schema:
            type: string
        "400":
          description: 请求解析失败
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /problem/choice/delete/{id}:
    delete:
      description: 删除选择题
      parameters:
      - description: 选择题ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 删除成功
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /problem/choice/update:
    put:
      description: 更新选择题(description为空或不传则维持原description,choices只需传需要更新的)
      parameters:
      - description: 选择题信息
        in: body
        name: problem
        required: true
        schema:
          $ref: '#/definitions/api.ChoiceProblemResponse'
      - description: 是否公开
        in: query
        name: is_public
        type: boolean
      responses:
        "200":
          description: 更新成功
          schema:
            type: string
        "400":
          description: 请求解析失败
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /register:
    post:
      description: 用户注册
      parameters:
      - description: 用户注册信息
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/api.RegisterInfo'
      responses:
        "200":
          description: 注册成功
          schema:
            type: string
        "400":
          description: 请求解析失败
          schema:
            type: string
        "409":
          description: 用户名已存在
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
  /reset-password:
    post:
      description: 用户修改密码
      parameters:
      - description: 用户修改密码信息
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/api.RegisterResponse'
      responses:
        "200":
          description: 修改成功
          schema:
            type: string
        "400":
          description: 请求解析失败
          schema:
            type: string
        "409":
          description: 用户不存在
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /upload/public:
    post:
      description: 上传公开文件
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: 文件 URL
          schema:
            type: string
        "400":
          description: 请求解析失败
          schema:
            type: string
        "403":
          description: 请求被禁止
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /user/info:
    get:
      description: 获取用户信息
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/api.UserInfoResponse'
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  /user/update:
    put:
      description: 更新用户信息
      parameters:
      - description: 用户信息
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/api.UserInfo'
      responses:
        "200":
          description: 更新成功
          schema:
            type: string
        "400":
          description: 请求解析失败
          schema:
            type: string
        default:
          description: 服务器错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
